# Generated by Django 5.0.3 on 2024-03-31 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('distinctive_trait', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('done', 'done')], default='pending', max_length=20)),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gateway.identityrecord')),
            ],
        ),
    ]
