# Generated by Django 5.0.3 on 2024-04-05 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_identityrecord_profession_marriagecertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityrecord',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gateway.identityrecord'),
        ),
        migrations.AlterField(
            model_name='identityrecord',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gateway.identityrecord'),
        ),
        migrations.DeleteModel(
            name='MarriageCertificate',
        ),
    ]
